spring:
    application:
        name: user
    datasource:
        url: jdbc:h2:mem:users_example
        username: test
        password: test
    h2:
        console:
            enabled: true
            path: /h2-ui
    jpa:
        hibernate:
            ddl-auto: update
    
server:
    port: 3002
